# Generated by Django 2.0.2 on 2018-02-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_per_sector', models.IntegerField()),
                ('sectors_per_cluster', models.IntegerField()),
                ('reserved', models.IntegerField()),
                ('fat32_size', models.IntegerField()),
            ],
        ),
    ]
